// Client-sichere Konstanten/Typen der Auftragsbörse (kein Server-Code).
export const CATEGORIES = [
  "Gebäudereinigung",
  "Hausmeisterservice",
  "Entrümpelung & Entsorgung",
  "Maler & Lackierer",
  "Elektriker",
  "Sanitär & Heizung",
  "Fliesenleger",
  "Bodenleger & Parkett",
  "Trockenbau & Innenausbau",
  "Dachdecker",
  "Zimmerei & Holzbau",
  "Gerüstbau",
  "Fenster & Türen",
  "Rollladen & Markisen",
  "Glaser",
  "Schlüsseldienst",
  "Schädlingsbekämpfung",
  "Schornsteinfeger",
  "Tischler & Schreiner",
  "Garten- & Landschaftsbau",
  "Pflaster- & Tiefbau",
  "Winterdienst",
  "Umzug & Transport",
  "Containerdienst",
  "Photovoltaik & Solar",
  "Heizung & Wärmepumpe",
  "Klima & Lüftung",
  "Sicherheitstechnik",
  "Sicherheits- & Wachdienst",
  "Personalvermittlung & Zeitarbeit",
  "Handwerk (Sonstiges)",
  "Agentur & Marketing",
  "IT & Web",
  "Steuerberatung & Buchhaltung",
  "Catering & Partyservice",
  "Sonstiges",
] as const;

export type CustomerType = "privat" | "gewerblich";
export type RequestStatus = "offen" | "geschlossen";
